### ISSUE TITLE
Texture mapping broken on OBJ+MTL

### ISSUE THREAD

**Issue by kbot** [wasabia/three_dart#146]
Something broke OBJ+MTL rendering post these versions:
flutter_gl: 0.0.13
three_dart: 0.0.9
three_dart_jsm: 0.0.4

It can be reproduced in the example webgl_loader_obj_mtl of this project. You can see the latest example renders like this:
![Screen Shot 2023-10-17 at 5 02 38 PM](https://github.com/wasabia/three_dart/assets/741931/9d77b893-5ca4-45c9-bffb-86a41bd501ed)

Any chance you can fix this? I can't use the old versions anymore because they rely on and old ffi and other packages collide

**Comment by Knightro63** [comment]
Hi @kbot,

Yes I did notice this as well. While they are working on getting a new version out could you please use this version of the repo.

```yaml
  flutter_gl: 0.0.21
  three_dart:
    git:
      url: https://github.com/Knightro63/three_dart.git
  three_dart_jsm:
    git:
      url: https://github.com/Knightro63/three_dart_jsm.git
```

Hope this helps
